### ISSUE TITLE
doesn't work for me - no changes in cpp json

### ISSUE THREAD

**Issue by amigo421** [maddouri/vscode-cmake-tools-helper#1]
just tried to use, VSCode 1.12.

for sure, select delete and reconfgiure for cmaketools, but no changes in c_cpp_properties.json
in other hand , this (by default ) doesn't contain the path to standard libraries and vscode/cpptools can't recognize standard headers location

**Comment by maddouri** [comment]
Thanks for reporting the issue.

Could you please try with the latest version of  **VS Code **Insiders** and the latest version of the extension? 

As for the standard libs' includes... you're right! I couldn't find how to extract them from CMake Tools :/ If you have ideas, feel free to submit them. I will do my best to implement them.

**Comment by amigo421** [comment]
initially I didn't understand  whats happened, and even raised the [request](https://github.com/Microsoft/vscode-cpptools/issues/795#event-1108210330) for cpptools developers.
don't know how but problem with standard headers was resolved. 

but damaged c_cpp_properties.json file is a real problem. 

okay I'll try insiders version and let you know

**Comment by maddouri** [comment]
Ok. Sorry for that. But please note that this behavior is mentioned in the extension's README:

> ### Mirroring the Information in cpptools
>
> Each time CMake Tools Helper is notified, the following happens:
>
> 1.CMake Tools Helper
>    1. Gets the current configuration and target name from CMake Tools
>    1. Overrides the content of c_cpp_properties.json using the information from step 1

**Comment by maddouri** [comment]
@amigo421 I was going over CMake Tools' code when I remembered that the current implementation of  CMake Tools Helper relies on  the `cmake.experimental.useCMakeServer` option to be `true`.

Please make sure that this option is enabled.

**Comment by maddouri** [comment]
Hi @amigo421 

Do you still face the issue after enabling CMake Server?

**Comment by amigo421** [comment]
sorry for delay, insiders build didn't solve the problem, 
the same issue, cmake server is enabled in CMakeTools by default. 
do you need dev console from vscode hel[p menu?

**Comment by maddouri** [comment]
Thanks for the feedback.

That's odd.. I did a few tests but couldn't find out why you would get such a problem.

If you have:
1. cmake.useCMakeServer set to true (restarting VSCode is necessary to apply this change)
1. Reconfigured the project (by erasing the cache then regenerating the project)
1. Selected a target (other than "all", "zero_check", etc.)

then, this extension should write a valid configuration to the cpptools' json file.

Sure, the dev console log might help, please consider sending it.

Also, if you're familiar with VSCode extension development, you could:
1. Clone this repo
1. Open it in VSCode
1. Press F5 to debug
1. If an exception is raised, VSCode should pinpoint its exact location with some info on why it happened

**Comment by amigo421** [comment]
okay, I'll try to debug and let you know about the results

**Comment by exploser** [comment]
Same thing happened to me literally 5 minutes ago.
Fixed it by changing build target from "all" (which was set by default for some reason) to "ALL_BUILD" (which was suggested in the dropdown).
Setting target to the one created with add_executable also works.

**Comment by maddouri** [comment]
@exploser Great! Thanks for the feedback.

I'd suggest selecting the targets created by add_executable or add_library. This way, this extension will set the proper includes and defines in cpptools' c_cpp_properties.json ;)

**Comment by ghita** [comment]
I get this, same problem with missing  includes
[Extension Host] rejected promise not handled within 1 second
h.logExtensionHostMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Invalid backend promise: Error: Invalid backend promise
    at new CMakeToolsWrapper (/Users/gheorghem/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/wrapper.js:46:40)
    at /Users/gheorghem/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/extension.js:17:23
    at Generator.next (<anonymous>)
    at /Users/gheorghem/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/extension.js:7:65
    at __awaiter (/Users/gheorghem/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/extension.js:3:12)
    at activate (/Users/gheorghem/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/extension.js:15:12)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:417918)
    at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:417703)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:417478
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:41973)

Using latest official vscode  &&  pluggins. Points to s
cmake-tools though

**Comment by mtgrasse** [comment]
I'm seeing the same symptoms but slightly different backtrace in the developer console:
[Extension Host] rejected promise not handled within 1 second
h.logExtensionHostMessage @ extensionHost.ts:320
shell.ts:443 Cannot read property 'forEach' of undefined: TypeError: Cannot read property 'forEach' of undefined
    at target (/Users/matgra01/.vscode/extensions/maddouri.cmake-tools-helper-0.1.1/out/src/c_cpp_properties.js:29:34)
    at configuration.parse (/Users/matgra01/.vscode/extensions/maddouri.cmake-tools-helper-0.1.1/out/src/c_cpp_properties.js:37:11)
    at new configuration (/Users/matgra01/.vscode/extensions/maddouri.cmake-tools-helper-0.1.1/out/src/c_cpp_properties.js:22:14)
    at prj.targets.forEach.tgt (/Users/matgra01/.vscode/extensions/maddouri.cmake-tools-helper-0.1.1/out/src/c_cpp_properties.js:75:54)
    at Array.forEach (native)
    at cfg.projects.forEach.prj (/Users/matgra01/.vscode/extensions/maddouri.cmake-tools-helper-0.1.1/out/src/c_cpp_properties.js:73:33)
    at Array.forEach (native)
    at configs.forEach.cfg (/Users/matgra01/.vscode/extensions/maddouri.cmake-tools-helper-0.1.1/out/src/c_cpp_properties.js:72:30)
    at Array.forEach (native)
    at c_cpp_properties.parse (/Users/matgra01/.vscode/extensions/maddouri.cmake-tools-helper-0.1.1/out/src/c_cpp_properties.js:71:21)
e.onUnexpectedError @ shell.ts:443

**Comment by tmchartrand** [comment]
I have the same error as above: "TypeError: Cannot read property 'forEach' of undefined"

**Comment by tmchartrand** [comment]
Looks like just need to check if target has filegroups at line 29 of c_cpp_properties.
Will test out if I get a chance.

**Comment by vadimcn** [comment]
Having the same issue: `TypeError: Cannot read property 'forEach' of undefined`

Here's what my c_cpp_properties looks like:
<details>
<summary>c_cpp_properties.json</summary>
<pre>
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/c++/5",
                "/usr/include/x86_64-linux-gnu/c++/5",
                "/usr/local/include",
                "/usr/include",
                "/usr/include/x86_64-linux-gnu",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include/c++/5",
                    "/usr/include/x86_64-linux-gnu/c++/5",
                    "/usr/local/include",
                    "/usr/include",
                    "/usr/include/x86_64-linux-gnu",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include",
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
</pre>
</details>

**Comment by vadimcn** [comment]
Yeah, looks like some targets just don't have the `fileGroups` property.   Can confirm that PR #7 fixes the issue.

**Comment by eldadroobol** [comment]
PR #7 fixes the issues for me as well.

**Comment by maddouri** [comment]
v0.2.0 includes #7

Is this issue still present?

**Comment by nergnezor** [comment]
Works well now!
